<?php

namespace AppBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByProject($project_id, $levels = 0)
    {
    	$em = $this->getEntityManager();
        if($levels === 0){
        	$paramArray = array('project_id' => $project_id);
        	$queryString = "SELECT m FROM AppBundle:Message m WHERE m.projectId = :project_id";
        } else {
            $paramArray = array('project_id' => $project_id, "levels" => $levels);
            $queryString = "SELECT m FROM AppBundle:Message m WHERE m.projectId = :project_id AND m.messageLevel <= :levels";
        }
    	$query = $em->createQuery($queryString)->setParameters($paramArray);
    	$products = $query->getResult();
    	return $products;
        //return $this->findBy(array('projectId' => $project_id));
    }


    public function findByThread($parent_message_id)
    {
        $em = $this->getEntityManager();
        if($levels === 0){
            $paramArray = array('project_id' => $project_id);
            $queryString = "SELECT m FROM AppBundle:Message m WHERE m.projectId = :project_id";
        } else {
            $paramArray = array('project_id' => $project_id, "levels" => $levels);
            $queryString = "SELECT m FROM AppBundle:Message m WHERE m.projectId = :project_id AND m.messageLevel <= :levels";
        }
        $query = $em->createQuery($queryString)->setParameters($paramArray);
        $products = $query->getResult();
        return $products;
        //return $this->findBy(array('projectId' => $project_id));
    }


}
